# Generated by Django 3.2.8 on 2021-10-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('M', 'Major'), ('N', 'Normal'), ('L', 'Later')], default='N', max_length=1)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
